INSERT INTO MENU (ID, NAME) VALUES (1, 'shots');
INSERT INTO MENU (ID, NAME) VALUES (2, 'shooters');
INSERT INTO MENU (ID, NAME) VALUES (3, 'longs');
INSERT INTO MENU (ID, NAME) VALUES (4, 'smoothie');
INSERT INTO MENU (ID, NAME) VALUES (5, 'non-alc');