services:
  db:
    container_name: postgres
    hostname: postgres
    image: postgres:15.6-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "my_bar"
    ports:
      - "5433:5432"
    expose:
      - 5433
    volumes:
      - postgres-data:/data/postgresql
  app:
    image: my-bar-backend:latest
    container_name: my-bar-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      KAFKA_BOOTSTRAP_SERVERS: broker:19092
    depends_on:
      - db
volumes:
  postgres-data: