server:
  servlet:
    contextPath: /api/bar
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.springframework.security: trace

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

spring:
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:8080
        introspection-endpoint: /oauth2/token-info
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:my_bar}?schema=${DATABASE_SCHEMA:public}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
  flyway:
    fail-on-missing-locations: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      spring.json.trusted.packages: "*"
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: mybar.events.common.serializer.MyBarJsonSerializer
    consumer:
      group-id: mb-events
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

my-bar:
  events:
    rates-topic-name: my_bar_cocktails.RATED
