CREATE TABLE BOTTLE (
  ID            VARCHAR(255) NOT NULL,
  BRAND_NAME    VARCHAR(255),
  IMAGE_URL     VARCHAR(255),
  IN_SHELF      BIT DEFAULT 0,
  PRICE         DECIMAL(19, 2),
  VOLUME        DOUBLE PRECISION,
  INGREDIENT_ID INTEGER      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE COCKTAIL (
  ID          VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255),
  IMAGE_URL   VARCHAR(255),
  MENU_ID     INTEGER,
  NAME        VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE COCKTAIL_TO_INGREDIENT (
  MEASUREMENT         VARCHAR(255),
  VOLUME        DOUBLE PRECISION,
  INGREDIENT_ID INTEGER,
  COCKTAIL_ID   VARCHAR(255),
  PRIMARY KEY (COCKTAIL_ID, INGREDIENT_ID)
);

CREATE TABLE INGREDIENT (
  GROUP_NAME VARCHAR(31) NOT NULL,
  ID         INTEGER     NOT NULL,
  KIND       VARCHAR(255),
  TYPE       VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE MENU (
  ID   INTEGER NOT NULL,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE BOTTLE
  ADD CONSTRAINT FK_BOTTLE_INGREDIENT_ID
FOREIGN KEY (INGREDIENT_ID)
REFERENCES INGREDIENT (ID);

ALTER TABLE COCKTAIL
  ADD CONSTRAINT FK_COCKTAIL_MENU_ID
FOREIGN KEY (MENU_ID)
REFERENCES MENU (ID);

ALTER TABLE COCKTAIL_TO_INGREDIENT
  ADD CONSTRAINT FK_COCKTAIL_TO_INGREDIENT_INGREDIENT_ID
FOREIGN KEY (INGREDIENT_ID)
REFERENCES INGREDIENT (ID);

ALTER TABLE COCKTAIL_TO_INGREDIENT
  ADD CONSTRAINT FK_COCKTAIL_TO_INGREDIENT_COCKTAIL_ID
FOREIGN KEY (COCKTAIL_ID)
REFERENCES COCKTAIL (ID);
