CREATE TABLE rates (
  STARS       INTEGER,
  RATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USERNAME    VARCHAR(255) NOT NULL,
  COCKTAIL_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY (COCKTAIL_ID, USERNAME)
);

ALTER TABLE rates
  ADD CONSTRAINT FK_USERNAME_TO_RATES_USERNAME
FOREIGN KEY (USERNAME)
REFERENCES users (USERNAME);

ALTER TABLE rates
  ADD CONSTRAINT FK_COCKTAIL_TO_RATES_COCKTAIL_ID
FOREIGN KEY (COCKTAIL_ID)
REFERENCES cocktail (ID);
